services:
    grafana:
        ports:
            - 3000:3000
        restart: always
        volumes:
            - grafana-volume:/var/lib/grafana
        image: grafana/grafana
    prometheus:
        ports:
            - 9090:9090
        restart: always
        volumes:
            - ${PWD}/config:/etc/prometheus
            - prometheus-volume:/prometheus
        image: prom/prometheus
    node-exporter:
        ports:
            - 9100:9100
        restart: always
        image: prom/node-exporter
volumes:
  grafana-volume:
  prometheus-volume:
