services:
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - ./grafana-config/provisioning:/etc/grafana/provisioning
            - grafana-data:/var/lib/grafana
        restart: always

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus-config:/etc/prometheus
        restart: always

    node-exporter:
        image: prom/node-exporter
        restart: always

volumes:
  grafana-data:
